language: python
python:
  - "3.9"
install:
  - pip install pipenv
  - pipenv install --dev
services:
  - postgresql
env:
  - SECRET_KEY=lba%2wx*46d$ga$2fwywc#gxyda4m589$pxbptm5rir_uuj8a2
before_script:
  - touch .env
  - echo SECRET_KEY=$SECRET_KEY >> .env
  - psql -c 'CREATE USER kevin WITH PASSWORD kevin;' -U postgres
  - psql -c 'CREATE DATABASE enlightenedpitchdb;' -U postgres
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - pytest
