# Generated by Django 3.2.7 on 2021-09-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloc',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
