# Generated by Django 3.2.7 on 2021-09-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finish',
            options={'verbose_name_plural': 'finishes'},
        ),
        migrations.AlterModelOptions(
            name='rarity',
            options={'verbose_name_plural': 'rarities'},
        ),
    ]
