# Generated by Django 3.2.7 on 2021-09-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='_type',
            field=models.IntegerField(choices=[(0, 'Action'), (1, 'Attack Reaction'), (2, 'Defense Reaction'), (3, 'Instant'), (4, 'Equipment'), (5, 'Weapon'), (6, 'Hero')]),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='stat',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='supertype',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
