# Generated by Django 3.2.7 on 2021-09-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sets',
            new_name='Set',
        ),
    ]
