# Generated by Django 3.2.7 on 2021-09-14 12:51

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_sets_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('_class', models.IntegerField(choices=[(0, 'Generic'), (1, 'Brute'), (2, 'Guardian'), (3, 'Ninja'), (4, 'Warrior'), (5, 'Mechanologist'), (6, 'Ranger'), (7, 'Runeblade'), (8, 'Wizard'), (9, 'Merchant'), (10, 'Shapeshifter'), (11, 'Illusionist')])),
                ('_type', models.IntegerField(choices=[(0, 'Non Attack Action'), (1, 'Attack Action'), (2, 'Attack Reaction'), (3, 'Defense Reaction'), (4, 'Instant'), (5, 'Equipment'), (6, 'Weapon'), (7, 'Hero')])),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Releasenote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=15, unique=True)),
                ('finish', models.CharField(choices=[('', 'Regular'), ('RF', 'Rainbow Foil'), ('CF', 'Cold Foil'), ('EA', 'Extended Art'), ('AA', 'Alternate Art')], default='', max_length=2)),
                ('image', models.ImageField(upload_to=backend.models.image_directory_path)),
                ('artist', models.CharField(max_length=30)),
                ('is_first_edition', models.BooleanField(null=True)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('R', 'Rare'), ('S', 'Super Rare'), ('M', 'Majestic'), ('L', 'Legendary'), ('F', 'Fabled'), ('P', 'Promo')], max_length=1)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.card')),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.set')),
            ],
        ),
        migrations.CreateModel(
            name='CardTalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.card')),
                ('talent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.talent')),
            ],
        ),
        migrations.CreateModel(
            name='CardSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.card')),
                ('subtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subtype')),
            ],
        ),
        migrations.CreateModel(
            name='CardStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.card')),
                ('stat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.stat')),
            ],
        ),
        migrations.CreateModel(
            name='CardReleasenote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.card')),
                ('releasenote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.releasenote')),
            ],
        ),
        migrations.CreateModel(
            name='CardKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.card')),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.keyword')),
            ],
        ),
    ]
