# Generated by Django 3.2.7 on 2021-09-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210921_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardkeyword',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='cardkeyword',
            old_name='keyword_id',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='cardreleasenote',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='cardreleasenote',
            old_name='releasenote_id',
            new_name='releasenote',
        ),
        migrations.RenameField(
            model_name='cardstat',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='cardstat',
            old_name='stat_id',
            new_name='stat',
        ),
        migrations.RenameField(
            model_name='cardsubtype',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='cardsubtype',
            old_name='subtype_id',
            new_name='subtype',
        ),
        migrations.RenameField(
            model_name='cardsupertype',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='cardsupertype',
            old_name='supertype_id',
            new_name='supertype',
        ),
        migrations.RenameField(
            model_name='cardtalent',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='cardtalent',
            old_name='talent_id',
            new_name='talent',
        ),
        migrations.RenameField(
            model_name='copy',
            old_name='printing_id',
            new_name='printing',
        ),
        migrations.RenameField(
            model_name='copy',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='deckcard',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='deckcard',
            old_name='deck_id',
            new_name='deck',
        ),
    ]
