# Generated by Django 3.2.7 on 2021-09-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_card_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasenote',
            name='text',
            field=models.CharField(max_length=5000),
        ),
    ]
