# Generated by Django 3.2.7 on 2021-09-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_releasenote_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasenote',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
