# Generated by Django 3.2.7 on 2021-09-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_card_bloc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='creator',
            new_name='user',
        ),
    ]
